### ISSUE TITLE
Quality of life enhancements for 1.0.1

### ISSUE THREAD

**Issue by TheSandvichMaker** [BredaUniversityGames/DXX-Raytracer#3]
Just writing these down here for reference:
- [x] Saving/loading of light settings for global lights and weapon lights.
- [x] Fix behaviour in the material editor when trying to save a material with its parameters set to default.
- [x] Add ability to change texture paths in material editor.
- [x] Add options for configuring headlights.
- [x] Add menu option for bilinear filtering.
- [x] Fix NaNs that can show up in shading.
- [x] Fix quick save loading
- [x] End level cutscenes are not lit properly
- [x] Spaceship in end-level cutscene is not visible
- [x] Weapons seem to shoot at changing intervals
- Seems to be a later fix of a source port, the OGL version from DXX-Retro does the same
- [x] UAV barriers for ping-pong render targets do not work correctly
- [x] Empty energy bar visible through UI elements

**Comment by Contingencyy** [comment]
- [] Fix quick save loading
- [] Spaceship in end-level cutscene is not visible
- [] Lasers seem to shoot at changing intervals
- [] UAV barriers for ping-pong textures do not work correctly
