### ISSUE TITLE
Descent 2 possibility with this?

### ISSUE THREAD

**Issue by Xavron** [BredaUniversityGames/DXX-Raytracer#5]
From what I understand Descent 2 is very similar for the engine? Might that be a possibility here or is it too different to work? Is that something you might think about also supporting? It boils down to one question though.

**Comment by enci** [comment]
I think most of the team members have moved on to other projects (at various companies) and it's up the community at this point.

**Comment by Contingencyy** [comment]
We know that Descent 2 is very similar to the original Descent indeed, so it would not be a difficult task to make the DXX-Raytracer work for Descent 2 as well. However, we won't be doing that, as @enci said, we moved on to other projects.
